export const AppError = {
  USER_EXIST: "User with this email exist",
  USER_NOT_FOUND: "User does not exist",
  WRONG_DATA: "Email or password is wrong",
  UNAUTHORIZED: "User is not authenticated",
  FORBIDDEN: "Forbidden resource",
  FAILED_SIGNUP: "Failed to sign up",
  FAILED_SIGNIN: "Failed to sign in! Invalid credentials or user does not exist",
  FAILED_REFRESH: "Failed to refresh session",
  SESSION_EXPIRED: "Session expired, please login again",
  ONE_DOCUMENT: "Please note that only one document is permitted in the collection. Should you wish to update or delete it, please do so.",
  NO_DOCUMENT: "There are no documents to be deleted",
  BOOKING_NOT_FOUND: "The booking could not be found",
  OPTIONS_NOT_FOUND: "The options could not be found",
  OPTIONS_TYPE_NOT_FOUND: "Option type not found",
  INVALID_PRICE: "Invalid price",
};
